In [3]:
import numpy as np
import pandas as pd

In [4]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [5]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [6]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [7]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [8]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [10]:
date['date'] = pd.to_datetime(date['date'])

In [12]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [13]:
#year
date['year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  year
91  2018-09-18         923       13       1  2018
28  2019-04-20        5501       16       1  2019
68  2018-10-18         588       16       1  2018
499 2018-09-28        1225       13      40  2018
201 2019-04-06        2357       14     104  2019

In [14]:
#month
date['month'] = date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  year  month
406 2018-11-20        1081       22       1  2018     11
846 2018-09-02        4457       22      80  2018      9
231 2018-08-28        4289       13       1  2018      8
477 2018-08-08         383       25      22  2018      8
382 2018-09-30        1935        2      48  2018      9

In [15]:
#day
date['day'] = date['date'].dt.day
date.sample(5)

          date  product_id  city_id  orders  year  month  day
18  2019-06-12        5630       14      31  2019      6   12
761 2019-04-16        2800       13       1  2019      4   16
959 2018-12-07        1700        8       2  2018     12    7
763 2018-11-25        1467       22      90  2018     11   25
437 2019-08-04        2830       14      21  2019      8    4

In [16]:
#month name
date['date_month_name'] = date['date'].dt.month_name()
date.head()

        date  product_id  city_id  orders  year  month  day date_month_name
0 2019-12-10        5628       25       3  2019     12   10        December
1 2018-08-15        3646       14     157  2018      8   15          August
2 2018-10-23        1859       25       1  2018     10   23         October
3 2019-08-17        7292       25       1  2019      8   17          August
4 2019-01-06        4344       25       3  2019      1    6         January

In [17]:
#day of week
date['dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,year,month,day,date_month_name,dow
0,2019-12-10,5628,25,3,2019,12,10,December,1
1,2018-08-15,3646,14,157,2018,8,15,August,2
2,2018-10-23,1859,25,1,2018,10,23,October,1
3,2019-08-17,7292,25,1,2019,8,17,August,5
4,2019-01-06,4344,25,3,2019,1,6,January,6

In [19]:
#day of week name
date['dow_name'] = date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,year,month,day,date_month_name,dow,dow_name
0,2019-12-10,5628,25,3,2019,12,10,December,Tuesday,Tuesday
1,2018-08-15,3646,14,157,2018,8,15,August,Wednesday,Wednesday
2,2018-10-23,1859,25,1,2018,10,23,October,Tuesday,Tuesday
3,2019-08-17,7292,25,1,2019,8,17,August,Saturday,Saturday
4,2019-01-06,4344,25,3,2019,1,6,January,Sunday,Sunday

In [20]:
#is weekend
date['is_weekend'] = np.where(date['dow_name'].isin(['Sunday','Saturday']),1,0)
date.head()

,date,product_id,city_id,orders,year,month,day,date_month_name,dow,dow_name,is_weekend
0,2019-12-10,5628,25,3,2019,12,10,December,Tuesday,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,15,August,Wednesday,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,23,October,Tuesday,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,17,August,Saturday,Saturday,1
4,2019-01-06,4344,25,3,2019,1,6,January,Sunday,Sunday,1

In [39]:
#week of the year
date['date_week'] = date['date'].dt.isocalendar().week
date.head()

,date,product_id,city_id,orders,year,month,day,date_month_name,dow,dow_name,is_weekend,date_week
0,2019-12-10,5628,25,3,2019,12,10,December,Tuesday,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,15,August,Wednesday,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,23,October,Tuesday,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,17,August,Saturday,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,6,January,Sunday,Sunday,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,8,October,Monday,Monday,0,41
996,2018-12-06,5521,7,1,2018,12,6,December,Thursday,Thursday,0,49
997,2019-05-07,487,26,14,2019,5,7,May,Tuesday,Tuesday,0,19
998,2019-03-03,1503,21,2,2019,3,3,March,Sunday,Sunday,1,9
999,2019-10-15,6371,7,22,2019,10,15,October,Tuesday,Tuesday,0,42

In [40]:
#quarter
date['quarter'] = date['date'].dt.quarter
date.head()

,date,product_id,city_id,orders,year,month,day,date_month_name,dow,dow_name,is_weekend,date_week,quarter
0,2019-12-10,5628,25,3,2019,12,10,December,Tuesday,Tuesday,0,50,4
1,2018-08-15,3646,14,157,2018,8,15,August,Wednesday,Wednesday,0,33,3
2,2018-10-23,1859,25,1,2018,10,23,October,Tuesday,Tuesday,0,43,4
3,2019-08-17,7292,25,1,2019,8,17,August,Saturday,Saturday,1,33,3
4,2019-01-06,4344,25,3,2019,1,6,January,Sunday,Sunday,1,1,1

In [42]:
#semester
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)
date.head()

,date,product_id,city_id,orders,year,month,day,date_month_name,dow,dow_name,is_weekend,date_week,quarter,semester
0,2019-12-10,5628,25,3,2019,12,10,December,Tuesday,Tuesday,0,50,4,2
1,2018-08-15,3646,14,157,2018,8,15,August,Wednesday,Wednesday,0,33,3,2
2,2018-10-23,1859,25,1,2018,10,23,October,Tuesday,Tuesday,0,43,4,2
3,2019-08-17,7292,25,1,2019,8,17,August,Saturday,Saturday,1,33,3,2
4,2019-01-06,4344,25,3,2019,1,6,January,Sunday,Sunday,1,1,1,1

In [43]:
#Extract Time elapsed between dates
import datetime

today = datetime.datetime.today()
today

datetime.datetime(2026, 3, 11, 0, 47, 39, 792859)

In [48]:
(today - date['date'])

0     2283 days 00:47:39.792859
1     2765 days 00:47:39.792859
2     2696 days 00:47:39.792859
3     2398 days 00:47:39.792859
4     2621 days 00:47:39.792859
                 ...
995   2711 days 00:47:39.792859
996   2652 days 00:47:39.792859
997   2500 days 00:47:39.792859
998   2565 days 00:47:39.792859
999   2339 days 00:47:39.792859
Name: date, Length: 1000, dtype: timedelta64[ns]

In [49]:
(today - date['date']).dt.days

0      2283
1      2765
2      2696
3      2398
4      2621
       ...
995    2711
996    2652
997    2500
998    2565
999    2339
Name: date, Length: 1000, dtype: int64

In [59]:
#weeks passed
np.round((today -date['date'])/ np.timedelta64(1, 'W'),0)

0      326.0
1      395.0
2      385.0
3      343.0
4      374.0
       ...
995    387.0
996    379.0
997    357.0
998    366.0
999    334.0
Name: date, Length: 1000, dtype: float64

In [61]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [66]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0