In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [19]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
df

    R&D Spend  Administration  Marketing Spend  Profit
0        17.0            14.0             47.0    19.0
1        16.0            15.0             44.0    19.0
2        15.0            10.0             41.0    19.0
3        14.0            12.0             38.0    18.0
4        14.0             9.0             37.0    17.0
5        13.0            10.0             36.0    16.0
6        13.0            15.0             13.0    16.0
7        13.0            15.0             32.0    16.0
8        12.0            15.0             31.0    15.0
9        12.0            11.0             30.0    15.0
10       10.0            11.0             23.0    15.0
11       10.0             9.0             25.0    14.0
12        9.0            13.0             25.0    14.0
13        9.0            14.0             25.0    13.0
14       12.0            16.0             26.0    13.0
15       11.0            12.0             26.0    13.0
16        8.0            12.0             26.0    13.0
17        9.0            15.0             28.0    13.0
18        9.0            11.0             29.0    12.0
19        9.0            15.0              0.0    12.0
20        8.0            11.0             30.0    12.0
21        8.0            15.0             30.0    11.0
22        7.0            12.0             30.0    11.0
23        7.0            11.0             30.0    11.0
24        8.0            10.0             14.0    11.0
25        6.0            14.0             14.0    11.0
26        8.0            14.0             13.0    11.0
27        7.0            13.0             35.0    11.0
28        7.0            18.0             12.0    10.0
29        7.0            15.0             11.0    10.0
30        6.0            12.0              9.0    10.0
31        6.0            15.0              9.0    10.0
32        6.0            13.0              5.0    10.0
33        6.0            10.0             21.0    10.0
34        5.0            16.0             21.0    10.0
35        5.0             9.0             21.0    10.0
36        3.0            13.0             20.0     9.0
37        4.0             5.0             20.0     9.0
38        2.0             7.0             19.0     8.0
39        4.0             8.0             17.0     8.0
40        3.0            12.0             17.0     8.0
41        3.0             8.0             16.0     8.0
42        2.0            10.0             15.0     7.0
43        2.0            13.0              4.0     7.0
44        2.0            15.0              3.0     7.0
45        0.0            12.0              0.0     6.0
46        0.0            12.0             30.0     5.0
47        0.0            14.0              0.0     4.0
48        0.0             5.0              0.0     4.0
49        0.0            12.0              5.0     1.0

In [20]:
df.shape

(50, 4)

In [21]:
df = df.iloc[:,:-1]

In [22]:
df

    R&D Spend  Administration  Marketing Spend
0        17.0            14.0             47.0
1        16.0            15.0             44.0
2        15.0            10.0             41.0
3        14.0            12.0             38.0
4        14.0             9.0             37.0
5        13.0            10.0             36.0
6        13.0            15.0             13.0
7        13.0            15.0             32.0
8        12.0            15.0             31.0
9        12.0            11.0             30.0
10       10.0            11.0             23.0
11       10.0             9.0             25.0
12        9.0            13.0             25.0
13        9.0            14.0             25.0
14       12.0            16.0             26.0
15       11.0            12.0             26.0
16        8.0            12.0             26.0
17        9.0            15.0             28.0
18        9.0            11.0             29.0
19        9.0            15.0              0.0
20        8.0            11.0             30.0
21        8.0            15.0             30.0
22        7.0            12.0             30.0
23        7.0            11.0             30.0
24        8.0            10.0             14.0
25        6.0            14.0             14.0
26        8.0            14.0             13.0
27        7.0            13.0             35.0
28        7.0            18.0             12.0
29        7.0            15.0             11.0
30        6.0            12.0              9.0
31        6.0            15.0              9.0
32        6.0            13.0              5.0
33        6.0            10.0             21.0
34        5.0            16.0             21.0
35        5.0             9.0             21.0
36        3.0            13.0             20.0
37        4.0             5.0             20.0
38        2.0             7.0             19.0
39        4.0             8.0             17.0
40        3.0            12.0             17.0
41        3.0             8.0             16.0
42        2.0            10.0             15.0
43        2.0            13.0              4.0
44        2.0            15.0              3.0
45        0.0            12.0              0.0
46        0.0            12.0             30.0
47        0.0            14.0              0.0
48        0.0             5.0              0.0
49        0.0            12.0              5.0

In [23]:
np.random.seed(9)
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
14       12.0            16.0             26.0
44        2.0            15.0              3.0

In [24]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

In [25]:
df.head()

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        NaN             5.0             20.0
2        15.0            10.0             41.0
14       12.0             NaN             26.0
44        2.0            15.0              NaN

In [26]:
# Step 1 - Impute all missing values with mean of respective col

df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [27]:
# 0th Iteration
df0

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37       9.25            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [28]:
# Remove the col1 imputed value
df1 = df0.copy()
df1.iloc[1,0] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.25            26.00
44        2.0           15.00            29.25

In [29]:
# Use first 3 except nan vali rows to build a model and use the last for prediction

X = df1.iloc[[0,2,3,4],1:3]
X

    Administration  Marketing Spend
21           15.00            30.00
2            10.00            41.00
14           11.25            26.00
44           15.00            29.25

In [30]:
y = df1.iloc[[0,2,3,4],0]
y

21     8.0
2     15.0
14    12.0
44     2.0
Name: R&D Spend, dtype: float64

In [31]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

/opt/anaconda3/envs/aloks_projects/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([23.14158651])

In [32]:
df1.iloc[1,0] = 23.14
df1

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [34]:
# Remove the col2 imputed value

df1.iloc[3,1] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
21       8.00            15.0            30.00
37      23.14             5.0            20.00
2       15.00            10.0            41.00
14      12.00             NaN            26.00
44       2.00            15.0            29.25

In [35]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[[0,1,2,4],[0,2]]
X

    R&D Spend  Marketing Spend
21       8.00            30.00
37      23.14            20.00
2       15.00            41.00
44       2.00            29.25

In [36]:
y = df1.iloc[[0,1,2,4],1]
y

21    15.0
37     5.0
2     10.0
44    15.0
Name: Administration, dtype: float64

In [37]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

/opt/anaconda3/envs/aloks_projects/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.06331285])

In [38]:
df1.iloc[3,1] = 11.06
df1

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.06            26.00
44       2.00           15.00            29.25

In [39]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.nan
df1

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00             30.0
37      23.14            5.00             20.0
2       15.00           10.00             41.0
14      12.00           11.06             26.0
44       2.00           15.00              NaN

In [40]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[0:4,0:2]
X

    R&D Spend  Administration
21       8.00           15.00
37      23.14            5.00
2       15.00           10.00
14      12.00           11.06

In [41]:
y = df1.iloc[0:4,-1]
y

21    30.0
37    20.0
2     41.0
14    26.0
Name: Marketing Spend, dtype: float64

In [42]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

/opt/anaconda3/envs/aloks_projects/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([31.56351448])

In [43]:
df1.iloc[4,-1] = 31.56

In [44]:
# After 1st Iteration
df1

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.06            26.00
44       2.00           15.00            31.56

In [45]:
# Subtract 0th iteration from 1st iteration
df1 - df0

    R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37      13.89            0.00             0.00
2        0.00            0.00             0.00
14       0.00           -0.19             0.00
44       0.00            0.00             2.31

In [58]:
df2 = df1.copy()

df2.iloc[1,0] = np.nan
df2

    R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.06            26.00
44        2.0           15.00            31.56

In [59]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

/opt/anaconda3/envs/aloks_projects/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([23.78627207])

In [60]:
df2.iloc[1,0] = 23.78
df2

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.78            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.06            26.00
44       2.00           15.00            31.56

In [62]:
df2.iloc[4,-1] = np.nan
X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

/opt/anaconda3/envs/aloks_projects/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([36.4836996])

In [64]:
df2.iloc[4,-1] = 36.48
df2

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.78            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.06            26.00
44       2.00           15.00            36.48

In [65]:
df2 - df1

    R&D Spend  Administration  Marketing Spend
21       0.00             0.0             0.00
37       0.64             0.0             0.00
2        0.00             0.0             0.00
14       0.00             0.0             0.00
44       0.00             0.0             4.92

In [67]:
df3 = df2.copy()
df3.iloc[1,0] = np.nan

df3

    R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.06            26.00
44        2.0           15.00            36.48

In [68]:
X = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

/opt/anaconda3/envs/aloks_projects/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([25.80819442])

In [69]:
df3.iloc[1,0] = 25.80

In [71]:
df3.iloc[3,1] = np.nan
X = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

/opt/anaconda3/envs/aloks_projects/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.83792914])

In [72]:
df3.iloc[3,1] = 11.83

In [74]:
df3.iloc[4,-1] = np.nan

X = df3.iloc[0:4,0:2]
y = df3.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

/opt/anaconda3/envs/aloks_projects/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([58.27881472])

In [75]:
df3.iloc[4,-1] = 58.27

In [76]:
df3

    R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37       25.8            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.83            26.00
44        2.0           15.00            58.27

In [77]:
df3 - df2

    R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37       2.02            0.00             0.00
2        0.00            0.00             0.00
14       0.00            0.77             0.00
44       0.00            0.00            21.79

In [78]:
#repeatd those iteration till we will not get all the values to 0